import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-5 flex justify-center min-h-screen">
        <main className="max-w-300 w-full gap-5 flex flex-col flex-1">
          <nav className="w-full flex gap-10">
            <Link href="/">Home</Link>
            <Link href="/portfolio">Portfolio</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
